# Step 1: Installation and Setup

In [1]:
# Installing TensorFlow
! pip install -q tensorflow-gpu

     |████████████████████████████████| 320.4MB 44kB/s 


In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.3.0


In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Step 2: Data Preprocessing

In [4]:
# Importing the dataset
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [12]:
# Checking the working directory
! ls

Churn_Modelling.csv  sample_data


In [13]:
# reading the file
dataset = pd.read_csv('Churn_Modelling.csv')

In [14]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [15]:
# Selecting the Independent and Dependent variables
x = dataset.drop(labels=['RowNumber','CustomerId','Surname','Exited'], axis=1)
y = dataset['Exited']

In [16]:
x.head(10)

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10
5          645     Spain    Male  ...          1               0        149756.71
6          822    France    Male  ...          1               1         10062.80
7          376   Germany  Female  ...          1               0        119346.88
8          501    France    Male  ...          0               1         74940.50
9          684    France    Male  ...          1               1         71725.73

[10 rows x 10 columns]

In [17]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [18]:
# Encoding the categorical data
from sklearn.preprocessing import LabelEncoder

In [19]:
label_1 = LabelEncoder()
x['Geography'] = label_1.fit_transform(x['Geography'])

In [21]:
x.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [22]:
label_2 = LabelEncoder()
x['Gender'] = label_2.fit_transform(x['Gender'])

In [23]:
x.head(8)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10
5          645          2       1  ...          1               0        149756.71
6          822          0       1  ...          1               1         10062.80
7          376          1       0  ...          1               0        119346.88

[8 rows x 10 columns]

In [24]:
# Avoiding the Dummy variable trap
x = pd.get_dummies(x, drop_first=True, columns=['Geography'])

In [25]:
x.head(8)

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1
5          645       1   44  ...        149756.71            0            1
6          822       1   50  ...         10062.80            0            0
7          376       0   29  ...        119346.88            1            0

[8 rows x 11 columns]

In [26]:
# Splitting the dataset into train and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [27]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [28]:
x_train

array([[ 0.16958176, -1.09168714, -0.46460796, ...,  1.10643166,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -0.74866447,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  1.48533467,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  1.41231994,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ...,  0.84432121,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ...,  0.32472465,
         1.75486502, -0.57369368]])

In [29]:
x_test

array([[-0.55204276, -1.09168714, -0.36890377, ...,  1.61085707,
         1.75486502, -0.57369368],
       [-1.31490297, -1.09168714,  0.10961719, ...,  0.49587037,
        -0.5698444 , -0.57369368],
       [ 0.57162971, -1.09168714,  0.30102557, ..., -0.42478674,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227,  0.91601335, -0.27319958, ...,  0.71888467,
        -0.5698444 ,  1.74309049],
       [-0.00566991,  0.91601335, -0.46460796, ..., -1.54507805,
         1.75486502, -0.57369368],
       [-0.79945688,  0.91601335, -0.84742473, ...,  1.61255917,
         1.75486502, -0.57369368]])

# Step 3: Building the Model

In [30]:
# Creating an object (Initilizing the ANN)
model = tf.keras.models.Sequential()

In [31]:
# Adding input layer and first hidden layer
# 1) units = 6
# 2) activation function = ReLU
# 3) input dimention = 11
model.add(tf.keras.layers.Dense(units=6, activation='relu', input_dim = 11))

In [32]:
# Adding second hidden layer
model.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [33]:
# Output layer
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [34]:
# Compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 72        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


# Step 4: Training the model

In [36]:
model.fit(x_train, y_train.to_numpy(), batch_size=10, epochs=20)

Epoch 1/20
800/800 [==============================] - 1s 977us/step - loss: 0.4915 - accuracy: 0.7904
Epoch 2/20
800/800 [==============================] - 1s 912us/step - loss: 0.4416 - accuracy: 0.8048
Epoch 3/20
800/800 [==============================] - 1s 968us/step - loss: 0.4270 - accuracy: 0.8131
Epoch 4/20
800/800 [==============================] - 1s 905us/step - loss: 0.4193 - accuracy: 0.8190
Epoch 5/20
800/800 [==============================] - 1s 863us/step - loss: 0.4141 - accuracy: 0.8265
Epoch 6/20
800/800 [==============================] - 1s 862us/step - loss: 0.4095 - accuracy: 0.8273
Epoch 7/20
800/800 [==============================] - 1s 862us/step - loss: 0.4052 - accuracy: 0.8288
Epoch 8/20
800/800 [==============================] - 1s 871us/step - loss: 0.4002 - accuracy: 0.8325
Epoch 9/20
800/800 [==============================] - 1s 857us/step - loss: 0.3943 - accuracy: 0.8346
Epoch 10/20
800/800 [==============================] - 1s 862us/step - loss: 0.387

# Step 5: Model evaluation and prediction

In [37]:
# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test.to_numpy())

63/63 [==============================] - 0s 747us/step - loss: 0.3371 - accuracy: 0.8625


In [38]:
print('Test Accuracy: {}'.format(test_acc))

Test Accuracy: 0.862500011920929


In [39]:
y_pred = model.predict_classes(x_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [40]:
print(y_pred)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [41]:
print(y_test)

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64


In [42]:
y_test = y_test.to_numpy()

In [43]:
print(y_pred[11]), print(y_test[11])

[0]
0


(None, None)

In [44]:
# confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1503   92]
 [ 183  222]]


In [45]:
acc_cm = accuracy_score(y_test, y_pred)
print(acc_cm)

0.8625
